### PR TITLE
docs: fix typo errors

### PR DESCRIPTION
**Pull request by Lampese**

### CODE REVIEW

**Review by MeowShe — APPROVED** [review]

**Comment by Lampese** [comment]
@MeowShe Now u see a f**king actions(build) was stopped(Expected — Waiting for status to be reported). I will change the protect rule of branch to force push it.

**Comment by Lampese** [comment]
@MeowShe Now u see a f**king actions(build) was stopped(Expected — Waiting for status to be reported). I will change the protect rule of branch to force push it.

**Comment by MeowShe** [comment]
> @MeowShe Now u see a f**king action(build) was stopped(Expected — Waiting for status to be reported). I will change the protect rule of branch to force push it.

holy shsosksyzijajwk

**Comment by Lampese** [comment]
> > @MeowShe Now u see a f**king action(build) was stopped(Expected — Waiting for status to be reported). I will change the protect rule of branch to force push it.
> 
> holy shsosksyzijajwk

I always cry whenever I face it.

**Comment by Lampese** [comment]
@MeowShe $\color{ Pink} {你} \color{rgb(0,248,0)} {告}\color{#008000} {诉}\color{Purple} {我}\color{Indigo} {为}\color{DarkSlateBlue} {什}\color{Blue} {么}$

**Pull request merged**
